### ISSUE TITLE
process.stdout.write shim misspells "debounce" every time

### ISSUE THREAD

**Issue by JamesMGreene** [Filirom1/front-tests#1]
I stumbled upon your repo via [your comment](https://github.com/visionmedia/mocha/issues/160#issuecomment-6772372) on a Mocha+PhantomJS issue thread.

I really like how your [`process.stdout.write` shim](https://github.com/Backbonist/front-tests/blob/master/lib/process.stdout.write.js) works with the [debouncing](http://unscriptable.com/2009/03/20/debouncing-javascript-methods/).  I was using throttling for my own stdout writer in my PhantomJS test runner but am now inspired to switch over to the debouncing technique you illustrated instead.

**Actual issue:**
Minorly enough, you misspelled the word as "debouce" every time (4 instances) in this shim.  The correct spelling is "debounce". I'd submit a pull request but it's _probably_ not worth it on this one. :smile:

**Comment by metaskills** [comment]
I had to let Google sort that one out for me while learning about "debounce" :)

**Comment by ghost** [comment]
Also misspelled example as "exemple", assuming this is meant to be in English.

**Comment by metaskills** [comment]
Inspired by this project, i just finished my own called mocha-phantomjs on github here http://metaskills.net/mocha-phantomjs/

**Comment by Filirom1** [comment]
Just dicovered your comments now. Sorry guys but I forgot to watch my own repos.

@metaskills your project rocks

**Comment by Filirom1** [comment]
Done in adaabec87e9bb5ec61c39af2e72f0e7d536f8422

Thanks
