### ISSUE TITLE
Link Sharing With mocha-phantomjs

### ISSUE THREAD

**Issue by metaskills** [Filirom1/front-tests#2]
This project inspired me to  learn the PhantomJS API, Mocha, and Node/NPMs. I wrote the mocha-phantomjs project located here on github. http://metaskills.net/mocha-phantomjs/

At the bottom, I share a few alternative links that point back to this project. Would you consider doing the same?

**Comment by Filirom1** [comment]
Of course.

Done in eb23967982f06664b0ece1c5662a3b30bd2c2336
